global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
